In [7]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels as sm
import matplotlib.pyplot as plt
import seaborn as sns

# **Question 4**

TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

We are going to conduct a Test of Independence using Chi-Square test with Contingency table
We need to check whether the mean of any of these samples are different or the same




*  H0:  Independence of categorical variables (defective % does not vary by centers)
*  H1: Dependence of categorical variables (defective % varies by centre and somewhat/significantly related)

In [8]:
centres= pd.read_csv('/content/Costomer+OrderForm.csv')
centres.head()

  Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [9]:
centres.describe()

       Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [11]:
centres.isnull().sum()

Phillippines    0
Indonesia       0
Malta           0
India           0
dtype: int64

In [15]:
# Checking data type
centres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB

In [20]:
# Checking Counts

print(centres['Phillippines'].value_counts(), '\n',    # '\n' is to end the line there
      centres['Indonesia'].value_counts(), '\n',
      centres['Malta'].value_counts(), '\n',
      centres['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
 Error Free    267
Defective      33
Name: Indonesia, dtype: int64
 Error Free    269
Defective      31
Name: Malta, dtype: int64
 Error Free    280
Defective      20
Name: India, dtype: int64

In [26]:
# Creating Contigency table

defective_error_free_table = np.array([[271, 267, 269, 280],[29, 33,31,20]])
defective_error_free_table

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [28]:
stats.chi2_contingency(defective_error_free_table)

Chi2ContingencyResult(statistic=3.858960685820355, pvalue=0.2771020991233135, dof=3, expected_freq=array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]]))

In [29]:
alpha = 0.05
pvalue = 0.2771020991233135


if pvalue < alpha:
  print("We Reject Null hypothesis defective % varies by centre and somewhat/significantly related and there is dependency")
else:
  print("We fail to Reject Null hypothesis because of lack of evidence")

We fail to Reject Null hypothesis because of lack of evidence

So, We fail to Reject Null hypothesis because of lack of evidence and  defective % does not vary by centre and there is no dependency on centres

---